import { ProductDetailView } from "@/components/eCommerce/ProductDetailedPage"

// Sample product data - in real app this would come from API/database
const sampleProduct = {
    id: "macbook-pro-16",
    name: "MacBook Pro 16-inch with M3 Pro Chip",
    images: [
        "/macbook-pro.png",
        "/macbook-air-m2-laptop.png",
        "/dell-xps-13-laptop.png",
        "/hp-pavilion-gaming-laptop.png",
    ],
    currentPrice: 199900,
    originalPrice: 249900,
    discount: 20,
    rating: 4.8,
    reviewCount: 324,
    description:
        "The most powerful MacBook Pro ever is here. With the blazing-fast M3 Pro chip, up to 18 hours of battery life, and a stunning Liquid Retina XDR display, it's the ultimate pro laptop for demanding workflows.",
    specifications: {
        Processor: "Apple M3 Pro chip with 12-core CPU",
        Memory: "18GB unified memory",
        Storage: "512GB SSD storage",
        Display: "16.2-inch Liquid Retina XDR display",
        Graphics: "18-core GPU",
        Battery: "Up to 18 hours video playback",
        Weight: "2.16 kg",
        Connectivity: "3x Thunderbolt 4, HDMI, SDXC, MagSafe 3",
        "Operating System": "macOS Sonoma",
        Warranty: "1 year limited warranty",
    },
    features: [
        "M3 Pro chip delivers exceptional performance for pro workflows",
        "16.2-inch Liquid Retina XDR display with 1000 nits sustained brightness",
        "Up to 18 hours of battery life for all-day productivity",
        "Advanced camera and audio for video calls and content creation",
        "Fast SSD storage and unified memory for smooth multitasking",
        "Three Thunderbolt 4 ports for versatile connectivity",
    ],
    inStock: true,
    category: "Laptops",
}

export default function ProductPage({ params }) {
    return (
        <div className="min-h-screen bg-background">
            <ProductDetailView product={sampleProduct} />
        </div>
    )
}

export const metadata = {
    title: "Product Detailed Page",
    description: "Generated by create next app",
};